# Generated by Django 4.1.13 on 2024-11-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0004_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created_at']},
        ),
    ]
