# Generated by Django 4.1.13 on 2024-12-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodie_app', '0008_remove_recipe_instructions_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='diet',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodie_app.category'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foodie_app.diet'),
        ),
    ]
